### ISSUE TITLE
Exception！

### ISSUE THREAD

**Issue by lifegit** [mcxiaoke/packer-ng-plugin#116]
java -jar packer-ng-2.0.0.jar generate  --channels=ch1,ch2,ch3 --output=C:\Users\6\Desktop\cmd\packer-ng-plugin-master\packer-ng-plugin-master\tools\aa --input=C:\Users\6\Desktop\cmd\packer-ng-plugin-master\packer-ng-plugin-master\tools\k.apk

//以上为命令，运行后，出现如下错误：

========== APK Packer ==========
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/apksig/apk/ApkFormatException : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at com.mcxiaoke.packer.cli.Main.doGenerate(Main.java:119)
        at com.mcxiaoke.packer.cli.Main.generate(Main.java:109)
        at com.mcxiaoke.packer.cli.Main.main(Main.java:34)

**Comment by mcxiaoke** [comment]
发 `java -version` 的结果看看，应该是不支持Java 6

**Comment by lifegit** [comment]
用您的极速渠道打包工具打包后，还需要重新给Apk签名吗

**Comment by lifegit** [comment]
使用脚本打包

**Comment by mcxiaoke** [comment]
不需要

**Comment by lifegit** [comment]
通过stdio3.0编译了一个release版本（已通过stdio签名,还未进行梆梆加固）。然后使用脚本打包(packer-ng generate --channels=ch1,ch2,ch3 --output=build/archives app.apk)，打包出来后验证渠道信息(packer-ng verify app.apk) 确实可以验证到(File: app.apk Signed: true Channel: ch3)，但是代码中(String channel = PackerNg.getChannel(context);)却返回null?

**Comment by lifegit** [comment]
1.另外在 stdio编译出的app中，是没有通过gradle写任何渠道号的。
2.因为项目必须要兼容到api 10.所以并没有使用REDAME中的引入方式，而是通过 implementation project(path: ':helper') 方式引入的。

**Comment by lifegit** [comment]
helper 的 build.gradle：

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:2.2.2"
    }
}

repositories {
    jcenter()
}

apply plugin: 'com.android.library'

dependencies {
    compile project(":common")
}

android {

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
        encoding "UTF-8"
    }

    compileSdkVersion compileSdk

    defaultConfig {
        versionName '2.0.0'
        versionCode 200
        minSdkVersion minSdk
        targetSdkVersion targetSdk
    }

    lintOptions {
        abortOnError false
        htmlReport true
    }
}

//--------------------------------------------------------------------
compileSdk ：25
minSdk：10
targetSdk：25

**Comment by lifegit** [comment]
再次感谢您。谢谢提供宝贵的工具。

**Comment by lifegit** [comment]
v2SigningEnabled 已经为true

 signingConfigs {
        debug {
            v1SigningEnabled true
            v2SigningEnabled true
        }
        release {
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

**Comment by lifegit** [comment]
您好，我又建了一个测试的demo 。然后按照REDAME中的引入方式在gradle中引入了依赖。然后通过stdio编译签名，脚本打包。然后在代码中获取渠道就正常。
请问如果要兼容api 10 我该怎么做呢？是否以上的操作疏忽遗漏了什么？您可以帮忙指导下吗？或者通过上述我的描述能看出我有什么操作不对的地方吗？
谢谢！

**Comment by lifegit** [comment]
兼容api的 common 的 build.gradle：

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
    }
}

repositories {
    jcenter()
}

apply plugin: 'java'

sourceCompatibility = 1.7
targetCompatibility = 1.7

dependencies {
    // JUnit and Mockito
    testCompile "junit:junit:4.12"
    testCompile "org.mockito:mockito-core:1.10.19"
    testCompile "commons-io:commons-io:2.5"
    testCompile 'com.android.tools.build:apksig:2.3.0'
    testCompile "com.mcxiaoke.next:core:1.5.0"
}

test {
    testLogging.showStandardStreams = true
}

javadoc {
    failOnError false
}

**Comment by lifegit** [comment]
您好，我又建了一个测试的demo 。然后按照REDAME中的引入方式在gradle中引入了依赖。然后通过stdio编译签名，脚本打包。然后在代码中获取渠道就正常。
请问如果要兼容api 10 我该怎么做呢？是否以上的操作疏忽遗漏了什么？您可以帮忙指导下吗？或者通过上述我的描述能看出我有什么操作不对的地方吗？
谢谢！

**Comment by lifegit** [comment]
再次感谢您。谢谢提供宝贵的工具。
